name: Hello world
on: workflow_dispatch
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
       - name: Hello step
         run: |
           echo "welcome to github actions"
           echo "all the best for your new project"
           echo "good luck haseena"
         
